export const languagesData =[
  { "name": "Albanian", "submitCode": "sq", "countryCode": "AL", "countryName": "Albania" },
  { "name": "Arabic", "submitCode": "ar", "countryCode": "SA", "countryName": "Saudi Arabia" },
  { "name": "Arabic (EGY)", "submitCode": "ar_EG", "countryCode": "EG", "countryName": "Egypt" },
  { "name": "Arabic (UAE)", "submitCode": "ar_AE", "countryCode": "AE", "countryName": "United Arab Emirates" },
  { "name": "Arabic (LBN)", "submitCode": "ar_LB", "countryCode": "LB", "countryName": "Lebanon" },
  { "name": "Arabic (MAR)", "submitCode": "ar_MA", "countryCode": "MA", "countryName": "Morocco" },
  { "name": "Arabic (QAT)", "submitCode": "ar_QA", "countryCode": "QA", "countryName": "Qatar" },
  { "name": "Azerbaijani", "submitCode": "az", "countryCode": "AZ", "countryName": "Azerbaijan" },
  { "name": "Belarusian", "submitCode": "be_BY", "countryCode": "BY", "countryName": "Belarus" },
  { "name": "Bengali", "submitCode": "bn", "countryCode": "BD", "countryName": "Bangladesh" },
  { "name": "Bengali (IND)", "submitCode": "bn_IN", "countryCode": "IN", "countryName": "India" },
  { "name": "Bulgarian", "submitCode": "bg", "countryCode": "BG", "countryName": "Bulgaria" },
  { "name": "Catalan", "submitCode": "ca", "countryCode": "ES", "countryName": "Spain" },
  { "name": "Chinese (CHN)", "submitCode": "zh_CN", "countryCode": "CN", "countryName": "China" },
  { "name": "Chinese (HKG)", "submitCode": "zh_HK", "countryCode": "HK", "countryName": "Hong Kong" },
  { "name": "Chinese (TAI)", "submitCode": "zh_TW", "countryCode": "TW", "countryName": "Taiwan" },
  { "name": "Croatian", "submitCode": "hr", "countryCode": "HR", "countryName": "Croatia" },
  { "name": "Czech", "submitCode": "cs", "countryCode": "CZ", "countryName": "Czech Republic" },
  { "name": "Danish", "submitCode": "da", "countryCode": "DK", "countryName": "Denmark" },
  { "name": "Dari", "submitCode": "prs_AF", "countryCode": "AF", "countryName": "Afghanistan" },
  { "name": "Dutch", "submitCode": "nl", "countryCode": "NL", "countryName": "Netherlands" },
  { "name": "Dutch (BEL)", "submitCode": "nl_BE", "countryCode": "BE", "countryName": "Belgium" },
  { "name": "English", "submitCode": "en", "countryCode": "US", "countryName": "United States" },
  { "name": "English (UK)", "submitCode": "en_GB", "countryCode": "GB", "countryName": "United Kingdom" },
  { "name": "English (US)", "submitCode": "en_US", "countryCode": "US", "countryName": "United States" },
  { "name": "English (UAE)", "submitCode": "en_AE", "countryCode": "AE", "countryName": "United Arab Emirates" },
  { "name": "English (AUS)", "submitCode": "en_AU", "countryCode": "AU", "countryName": "Australia" },
  { "name": "English (CAN)", "submitCode": "en_CA", "countryCode": "CA", "countryName": "Canada" },
  { "name": "English (GHA)", "submitCode": "en_GH", "countryCode": "GH", "countryName": "Ghana" },
  { "name": "English (IRL)", "submitCode": "en_IE", "countryCode": "IE", "countryName": "Ireland" },
  { "name": "English (IND)", "submitCode": "en_IN", "countryCode": "IN", "countryName": "India" },
  { "name": "English (JAM)", "submitCode": "en_JM", "countryCode": "JM", "countryName": "Jamaica" },
  { "name": "English (MYS)", "submitCode": "en_MY", "countryCode": "MY", "countryName": "Malaysia" },
  { "name": "English (NZL)", "submitCode": "en_NZ", "countryCode": "NZ", "countryName": "New Zealand" },
  { "name": "English (QAT)", "submitCode": "en_QA", "countryCode": "QA", "countryName": "Qatar" },
  { "name": "English (SGP)", "submitCode": "en_SG", "countryCode": "SG", "countryName": "Singapore" },
  { "name": "English (UGA)", "submitCode": "en_UG", "countryCode": "UG", "countryName": "Uganda" },
  { "name": "English (ZAF)", "submitCode": "en_ZA", "countryCode": "ZA", "countryName": "South Africa" },
  { "name": "Estonian", "submitCode": "et", "countryCode": "EE", "countryName": "Estonia" },
  { "name": "Filipino", "submitCode": "fil", "countryCode": "PH", "countryName": "Philippines" },
  { "name": "Finnish", "submitCode": "fi", "countryCode": "FI", "countryName": "Finland" },
  { "name": "French", "submitCode": "fr", "countryCode": "FR", "countryName": "France" },
  { "name": "French (BEL)", "submitCode": "fr_BE", "countryCode": "BE", "countryName": "Belgium" },
  { "name": "French (CAN)", "submitCode": "fr_CA", "countryCode": "CA", "countryName": "Canada" },
  { "name": "French (CHE)", "submitCode": "fr_CH", "countryCode": "CH", "countryName": "Switzerland" },
  { "name": "French (CIV)", "submitCode": "fr_CI", "countryCode": "CI", "countryName": "Côte d'Ivoire" },
  { "name": "French (MAR)", "submitCode": "fr_MA", "countryCode": "MA", "countryName": "Morocco" },
  { "name": "Georgian", "submitCode": "ka", "countryCode": "GE", "countryName": "Georgia" },
  { "name": "German", "submitCode": "de", "countryCode": "DE", "countryName": "Germany" },
  { "name": "German (AUT)", "submitCode": "de_AT", "countryCode": "AT", "countryName": "Austria" },
  { "name": "German (CHE)", "submitCode": "de_CH", "countryCode": "CH", "countryName": "Switzerland" },
  { "name": "Greek", "submitCode": "el", "countryCode": "GR", "countryName": "Greece" },
  { "name": "Gujarati", "submitCode": "gu", "countryCode": "IN", "countryName": "India" },
  { "name": "Hausa", "submitCode": "ha", "countryCode": "NG", "countryName": "Nigeria" },
  { "name": "Hebrew", "submitCode": "he", "countryCode": "IL", "countryName": "Israel" },
  { "name": "Hindi", "submitCode": "hi", "countryCode": "IN", "countryName": "India" },
  { "name": "Hungarian", "submitCode": "hu", "countryCode": "HU", "countryName": "Hungary" },
  { "name": "Indonesian", "submitCode": "id", "countryCode": "ID", "countryName": "Indonesia" },
  { "name": "Irish", "submitCode": "ga", "countryCode": "IE", "countryName": "Ireland" },
  { "name": "Italian", "submitCode": "it", "countryCode": "IT", "countryName": "Italy" },
  { "name": "Japanese", "submitCode": "ja", "countryCode": "JP", "countryName": "Japan" },
  { "name": "Kannada", "submitCode": "kn", "countryCode": "IN", "countryName": "India" },
  { "name": "Kazakh", "submitCode": "kk", "countryCode": "KZ", "countryName": "Kazakhstan" },
  { "name": "Kinyarwanda", "submitCode": "rw_RW", "countryCode": "RW", "countryName": "Rwanda" },
  { "name": "Korean", "submitCode": "ko", "countryCode": "KR", "countryName": "South Korea" },
  { "name": "Kyrgyz (Kyrgyzstan)", "submitCode": "ky_KG", "countryCode": "KG", "countryName": "Kyrgyzstan" },
  { "name": "Lao", "submitCode": "lo", "countryCode": "LA", "countryName": "Laos" },
  { "name": "Latvian", "submitCode": "lv", "countryCode": "LV", "countryName": "Latvia" },
  { "name": "Lithuanian", "submitCode": "lt", "countryCode": "LT", "countryName": "Lithuania" },
  { "name": "Macedonian", "submitCode": "mk", "countryCode": "MK", "countryName": "North Macedonia" },
  { "name": "Malay", "submitCode": "ms", "countryCode": "MY", "countryName": "Malaysia" },
  { "name": "Malayalam", "submitCode": "ml", "countryCode": "IN", "countryName": "India" },
  { "name": "Marathi", "submitCode": "mr", "countryCode": "IN", "countryName": "India" }
]



export const up_arrow_svg = `<svg class="arrow-icon" width="12" height="7" viewBox="0 0 12 7" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M11 6L6 1L1 6" stroke="#1F2937" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`
export const down_arrow_svg = `<svg class="arrow-icon" width="12" height="7" viewBox="0 0 12 7" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M11 6L6 1L1 6" stroke="#1F2937" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" transform="rotate(180 6 3.5)"/></svg>`
